modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/Mrthomas20121/TFC-Metallum/issues"

[[mods]]
modId="tfc_metallum"
version="1.0.2"
displayName="Metallum"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tfc_metallum"
authors="Mrthomas20121"
description='''
Add metals and ores from other mods to TFC.
'''

[[dependencies.tfc_metallum]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.tfc_metallum]]
    modId="tfc"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"